### PR TITLE
(For Aaron) Partner python client change for limited account return

### PR DESCRIPTION
**Pull request by nickhurlburt**
@abeppu cc @yschatzberg

### CODE REVIEW

**Comment by abeppu** [comment]
Seems reasonable. Could you add a test case, or expand this one https://github.com/SiftScience/sift-partner-python/blob/master/tests/client_test.py#L383 ?

**Comment by nickhurlburt** [comment]
Test case has been added.

**Comment by nickhurlburt** [comment]
This is updated

**Comment by abeppu** [comment]
LGTM

**Pull request merged**
